module.exports = (sequelize, DataTypes) => {
  const SupportWorker = sequelize.define('support_worker', {
    user_ref_id: DataTypes.INTEGER,
    about_you: DataTypes.TEXT,
    gender: DataTypes.STRING,
    self_describe_explain: DataTypes.STRING,
    cultural_diversity: DataTypes.STRING,
    is_english_main_language: DataTypes.STRING,
    main_language: DataTypes.INTEGER,
    other_language: DataTypes.STRING,
    emergency_name: DataTypes.STRING,
    emergency_email: DataTypes.STRING,
    emergency_contact: DataTypes.STRING,
    emergency_relationship: DataTypes.STRING,
    any_health_conditions: DataTypes.STRING,
    any_health_conditions_details: DataTypes.TEXT,
    any_existing_injury: DataTypes.STRING,
    any_existing_injury_details: DataTypes.TEXT,
    clad_background: DataTypes.STRING,
    identify_as_lesbian: DataTypes.STRING,
    any_guilt: DataTypes.STRING,
    work_status: DataTypes.INTEGER,
    availability: DataTypes.INTEGER,
    days_availability: DataTypes.JSON,
    days_availability_from: DataTypes.STRING,
    days_availability_to: DataTypes.STRING,
    days_availability_na: DataTypes.STRING,
    availability_hour_range_dr_ref_id: DataTypes.INTEGER,
    willing_to_provide: DataTypes.STRING,
    willing_to_provide_other: DataTypes.TEXT,
    have_experience: DataTypes.STRING,
    years_of_experience: DataTypes.INTEGER,
    work_experience: DataTypes.JSON,
    work_experience_job_title: DataTypes.STRING,
    work_experience_company_name: DataTypes.STRING,
    work_experience_industry: DataTypes.STRING,
    work_experience_job_role: DataTypes.STRING,
    work_experience_still_working: DataTypes.STRING,
    work_experience_start_date: DataTypes.STRING,
    work_experience_end_date: DataTypes.STRING,
    further_experience: DataTypes.STRING,
    further_experience_other: DataTypes.TEXT,
    gender_preferences: DataTypes.STRING,
    gender_preferences_other: DataTypes.TEXT,
    have_car: DataTypes.STRING,
    is_car_insurance: DataTypes.STRING,
    km_to_travel: DataTypes.INTEGER,
    km_to_travel_other: DataTypes.TEXT,
    status: DataTypes.STRING,
  }, {
    freezeTableName: true,//Create Table with Model Name
    // tableName: 'user'
  });
  return SupportWorker;
}//End module export
